name: Update README
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: anuraghazra/github-readme-stats@master
        with:
          COMMITTER_TOKEN: ${{ secrets.TOKEN }}

      - uses: nirzak/streak-stats-action@v1
        with:
          username: AmirrrrMH

      - name: Top Languages
        run: |
          curl -H "Authorization: token ${{ secrets.TOKEN }}" \
            https://api.github.com/users/AmirrrrMH/repos?per_page=100&type=all \
            | jq -r '.[]?.language' | grep -v null | sort | uniq -c | sort -nr \
            | head -10 | awk '{print $2}' | paste -sd, - | sed 's/,/, /g' > l
          sed -i 's|<!-- LANGUAGES-OVERVIEW:START -->.*<!-- LANGUAGES-OVERVIEW:END -->|<!-- LANGUAGES-OVERVIEW:START -->\nTop Languages: '"$(cat l)"'\n<!-- LANGUAGES-OVERVIEW:END -->|' README.md

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git diff --quiet || git commit -m "Auto update"
          git push
